### ISSUE TITLE
difficulty running start branch

### ISSUE THREAD

**Issue by aandronic** [onehungrymind/angular-reactive-workshop#3]
On start branch, unable start app, getting
`1] Module build failed (from C:/.../Desktop/angular-reactive-workshop/node_modules/sass-loader/lib/loader.js):
[1] Error: Cannot find module 'node-sass'`

**Comment by laniehei** [comment]
Have you run `npm install` on the project? Let me know if this doesn't work. I can't recreate this issue on my end.
